//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKACCOUNT
    {
        public string BACSREF { get; set; }
        public string ACCOUNTTYPE { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string IBAN { get; set; }
        public string ADDITIONALREFERENCE { get; set; }
        public string BANKNAME { get; set; }
        public string REFERENCE { get; set; }
        public string NOMACCOUNT { get; set; }
        public string SWIFTCODE { get; set; }
        public string BANKACCOUNTNAME { get; set; }
        public string BRANCH { get; set; }
        public string ISCOMPANY { get; set; }
        public string CHEQUENAME { get; set; }
    }
}
