//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND
    {
        public BOND()
        {
            this.GOVBONDINTERESTSCHEDULEs = new HashSet<GOVBONDINTERESTSCHEDULE>();
        }
    
        public string REFERENCE { get; set; }
        public string FINANCIALINSTITUTION_REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string BONDID { get; set; }
        public string BONDTYPE { get; set; }
        public string SEQUENCENUMBER { get; set; }
        public Nullable<decimal> FACEVALUE { get; set; }
        public Nullable<System.DateTime> CHEQUEDATE { get; set; }
        public string CHEQUEREFERENCE { get; set; }
        public Nullable<decimal> CHEQUEAMOUNT { get; set; }
        public Nullable<decimal> CHEQUECLEARINGCHARGE { get; set; }
        public Nullable<System.DateTime> BONDISSUEDATE { get; set; }
        public Nullable<decimal> TENURE { get; set; }
        public string TENURETERM { get; set; }
        public Nullable<decimal> TERMSINDAYS { get; set; }
        public string INTERESTPAYMENTPERIOD { get; set; }
        public Nullable<System.DateTime> MATURITYDATE { get; set; }
        public Nullable<decimal> OFFERRATE { get; set; }
        public Nullable<decimal> COUPONRATE { get; set; }
        public Nullable<decimal> BUYINGPRICE { get; set; }
        public Nullable<decimal> COSTPRICE { get; set; }
        public Nullable<decimal> PREMIUMPAID { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> COMMISSION { get; set; }
        public Nullable<decimal> HOLDINGINTERESTPAID { get; set; }
        public Nullable<decimal> TOTALPURCHASEAMOUNT { get; set; }
        public Nullable<decimal> TOTALCOMMISSIONGAIN { get; set; }
        public string INTERESTMODE { get; set; }
        public Nullable<decimal> GROSSINTEREST { get; set; }
        public Nullable<decimal> SOURCETAX { get; set; }
        public Nullable<decimal> EXCISEDUTY { get; set; }
        public Nullable<decimal> OTHERCHARGE { get; set; }
        public string COMPOUNDINTERESTTYPE { get; set; }
        public string COMPOUNDINTERESTINTERVAL { get; set; }
        public Nullable<decimal> ANNUALDAYS { get; set; }
        public string STATUS { get; set; }
        public string ACCEPTEDBY { get; set; }
        public Nullable<System.DateTime> ACCEPTEDDATE { get; set; }
        public string REJECTEDBY { get; set; }
        public Nullable<System.DateTime> REJECTEDDATE { get; set; }
        public Nullable<decimal> HOLDINGPERIOD { get; set; }
        public Nullable<decimal> NETINTEREST { get; set; }
        public Nullable<System.DateTime> OPENINGDATE { get; set; }
        public string REMARKS { get; set; }
        public string AUCTION { get; set; }
        public Nullable<System.DateTime> AUCTIONDATE { get; set; }
        public Nullable<System.DateTime> ENCASHEDDATE { get; set; }
    
        public virtual FINANCIALINSTITUTION FINANCIALINSTITUTION { get; set; }
        public virtual ICollection<GOVBONDINTERESTSCHEDULE> GOVBONDINTERESTSCHEDULEs { get; set; }
    }
}
