//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDENCASHMENT
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string BONDID { get; set; }
        public string MRNO { get; set; }
        public Nullable<System.DateTime> MRDATE { get; set; }
        public Nullable<System.DateTime> ENCASHMENTDATE { get; set; }
        public Nullable<System.DateTime> RECEIVEDON { get; set; }
        public Nullable<System.DateTime> INTERESTFROM { get; set; }
        public Nullable<System.DateTime> INTERESTTO { get; set; }
        public Nullable<decimal> GROSSINTEREST { get; set; }
        public Nullable<decimal> SOURCETAX { get; set; }
        public Nullable<decimal> EXCISEDUTY { get; set; }
        public Nullable<decimal> OTHERCHARGE { get; set; }
        public Nullable<decimal> NETINTEREST { get; set; }
    }
}
