//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        public Nullable<decimal> ACRANGETO { get; set; }
        public string BRANCHTYPE { get; set; }
        public string STATUS { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string REFERENCE { get; set; }
        public Nullable<decimal> ACCOUNTFEE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ACRANGEFROM { get; set; }
        public string CODE { get; set; }
        public string WEB { get; set; }
        public Nullable<decimal> COMMMISSIONRATE { get; set; }
        public string PREFIX { get; set; }
        public string MERCHANTBANKNOMINAL { get; set; }
        public string TRADEBOUGHTPOSTING { get; set; }
        public string TRADESOLDPOSTING { get; set; }
        public string COMMISSIONPOSTING { get; set; }
        public string CSETRADEBOUGHTPOSTING { get; set; }
        public string CSETRADESOLDPOSTING { get; set; }
        public string CSECOMMISSIONPOSTING { get; set; }
    }
}
