//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHDIVIDENDDECLARATION
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string INSTRUMENTACREF { get; set; }
        public string ISIN { get; set; }
        public Nullable<decimal> SHAREQTY { get; set; }
        public Nullable<decimal> NETCASHDIVIDEND { get; set; }
        public Nullable<System.DateTime> CASHRECEIVEDDATE { get; set; }
        public Nullable<decimal> GROSSAMOUNT { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public string REFERENCENO { get; set; }
    
        public virtual INSTRUMENT INSTRUMENT { get; set; }
    }
}
