//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGEHEAD
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string CHARGETYPE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string ISPERCENTAGE { get; set; }
        public string ISACTIVE { get; set; }
        public string REFERENCE { get; set; }
    }
}
