//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORPORATEACTION
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string INVESTORREF { get; set; }
        public string PROCFLAG { get; set; }
        public Nullable<decimal> LOCKINBALANCE { get; set; }
        public string ISIN { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string EXCEPTION { get; set; }
        public string ISEXCEPTION { get; set; }
        public string ISCREDIT { get; set; }
        public string SEQUENCENO { get; set; }
        public Nullable<decimal> PREMIUM { get; set; }
        public Nullable<decimal> FREEZEBALANCE { get; set; }
        public Nullable<System.DateTime> IMPORTDATE { get; set; }
        public string CATYPE { get; set; }
        public Nullable<System.DateTime> EFFECTIVEDATE { get; set; }
        public string BOID { get; set; }
        public Nullable<decimal> FREEBALANCE { get; set; }
        public string INSTRUMENTNAME { get; set; }
        public string DRCRFLAG { get; set; }
    }
}
