//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMATCONFIRM
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string BALANCETYPE { get; set; }
        public string EXCEPTIONDETAILS { get; set; }
        public string INVESTORNAME { get; set; }
        public string PROCESSEDSTATUS { get; set; }
        public string ISIN { get; set; }
        public Nullable<decimal> ACCEPTEDQTY { get; set; }
        public string CERTNO { get; set; }
        public string ISEXCEPTION { get; set; }
        public string DRF { get; set; }
        public string INVESTORACREF { get; set; }
        public string DRN { get; set; }
        public string ISDEFAULTAVGCHANGE { get; set; }
        public Nullable<System.DateTime> BUSINESSDATE { get; set; }
        public string CERTSTATUS { get; set; }
        public string STATUS { get; set; }
        public string FOLIONO { get; set; }
        public Nullable<decimal> CERTQTY { get; set; }
        public Nullable<decimal> AVGCOST { get; set; }
        public string DNREND { get; set; }
        public Nullable<decimal> REQUESTEDQTY { get; set; }
        public string BOID { get; set; }
        public string INSTRUMENTNAME { get; set; }
        public Nullable<decimal> REJECTEDQTY { get; set; }
        public string DNRSTART { get; set; }
        public Nullable<System.DateTime> LOCKINEXPIRY { get; set; }
        public Nullable<decimal> LOCKINBALANCE { get; set; }
    }
}
