//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSITORYSETTING
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string FILENAME { get; set; }
        public Nullable<decimal> CHARGERATE { get; set; }
        public Nullable<decimal> MINIMUMFEE { get; set; }
        public string METHODNAME { get; set; }
        public Nullable<short> SEQ { get; set; }
    }
}
