//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDRINTEREST
    {
        public string REFERENCE { get; set; }
        public string FIXEDDEPOSIT_REFERENCE { get; set; }
        public Nullable<decimal> PRINCIPALAMOUNT { get; set; }
        public Nullable<decimal> RATEOFINTEREST { get; set; }
        public Nullable<System.DateTime> FROMDATE { get; set; }
        public Nullable<System.DateTime> TODATE { get; set; }
        public Nullable<decimal> GROSSINTEREST { get; set; }
        public Nullable<decimal> TAXRATE { get; set; }
        public Nullable<decimal> SOURCETAX { get; set; }
        public Nullable<decimal> EXCISEDUTY { get; set; }
        public Nullable<decimal> OTHERCHARGE { get; set; }
        public Nullable<decimal> NETINTERESTRECEIVABLE { get; set; }
        public Nullable<decimal> AMOUNTRECEIVABLE { get; set; }
        public Nullable<decimal> COMPOUNDVALUE { get; set; }
        public Nullable<decimal> TAXUPONGROSS { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<decimal> PRICIPALUPONNET { get; set; }
    
        public virtual FIXEDDEPOSIT FIXEDDEPOSIT { get; set; }
    }
}
