//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDRPROPOSALDETAIL
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string FDRPROPOSAL_REFERENCE { get; set; }
        public string FINANCIALINSTITUTION_REFERENCE { get; set; }
        public string TERMS { get; set; }
        public Nullable<decimal> TENURE { get; set; }
        public string STATUS { get; set; }
        public string ACCEPTEDBY { get; set; }
        public Nullable<System.DateTime> ACCEPTEDDATE { get; set; }
        public string REJECTEDBY { get; set; }
        public Nullable<System.DateTime> REJECTEDDATE { get; set; }
        public Nullable<decimal> TENURE2 { get; set; }
        public string TERM2 { get; set; }
        public Nullable<decimal> TENURE3 { get; set; }
        public string TERM3 { get; set; }
        public string BRANCH_REFERENCE { get; set; }
        public Nullable<decimal> CURRENTHOLDING { get; set; }
        public Nullable<decimal> PRINCIPALAMOUNT { get; set; }
        public Nullable<decimal> EXISTINGCAPLIMIT { get; set; }
        public Nullable<decimal> PERCENTAGEOFTOTALFDR { get; set; }
        public Nullable<decimal> NPL { get; set; }
        public Nullable<decimal> OFFERRATE { get; set; }
        public Nullable<int> ANNUALDAYS { get; set; }
        public string INTERESTMODE { get; set; }
        public Nullable<decimal> OFFERRATE3 { get; set; }
        public Nullable<decimal> OFFERRATE2 { get; set; }
        public string INTERESTMODE1 { get; set; }
        public string INTERESTMODE3 { get; set; }
        public string INTERESTMODE2 { get; set; }
        public Nullable<decimal> TENURE1 { get; set; }
        public string TERM1 { get; set; }
        public Nullable<decimal> OFFERRATE1 { get; set; }
        public string INTERESTMODE4 { get; set; }
        public Nullable<decimal> TENURE4 { get; set; }
        public string TERM4 { get; set; }
        public Nullable<decimal> OFFERRATE4 { get; set; }
    
        public virtual FDRPROPOSAL FDRPROPOSAL { get; set; }
        public virtual FIBRANCH FIBRANCH { get; set; }
        public virtual FINANCIALINSTITUTION FINANCIALINSTITUTION { get; set; }
    }
}
