//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIBRANCH
    {
        public FIBRANCH()
        {
            this.FDRNOTEs = new HashSet<FDRNOTE>();
            this.FDRPROPOSALDETAILS = new HashSet<FDRPROPOSALDETAIL>();
            this.FIXEDDEPOSITs = new HashSet<FIXEDDEPOSIT>();
        }
    
        public string REFERENCE { get; set; }
        public string CODE { get; set; }
        public string ROUTINGNUMBER { get; set; }
        public string SWIFTCODE { get; set; }
        public string DISTRICTCODE { get; set; }
        public string DISTRICTNAME { get; set; }
        public string ADDRESSLINE1 { get; set; }
        public string ADDRESSLINE2 { get; set; }
        public string POSTCODE { get; set; }
        public string CONTACTPERSON { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string FINANCIALINSTITUTION_REFERENCE { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<FDRNOTE> FDRNOTEs { get; set; }
        public virtual ICollection<FDRPROPOSALDETAIL> FDRPROPOSALDETAILS { get; set; }
        public virtual FINANCIALINSTITUTION FINANCIALINSTITUTION { get; set; }
        public virtual ICollection<FIXEDDEPOSIT> FIXEDDEPOSITs { get; set; }
    }
}
