//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUMENTCATEGORY
    {
        public INSTRUMENTCATEGORY()
        {
            this.INSTRUMENTs = new HashSet<INSTRUMENT>();
        }
    
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STOCKEXCHANGE { get; set; }
        public string ALLOWNETTING { get; set; }
        public string ISNONMARGINABLE { get; set; }
        public Nullable<long> SETTLEMENTDAYS { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<INSTRUMENT> INSTRUMENTs { get; set; }
    }
}
