//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTORPROFILE
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string MIDDLENAME { get; set; }
        public byte[] PHOTO { get; set; }
        public Nullable<System.DateTime> SETUPDATE { get; set; }
        public string MOBILE { get; set; }
        public string PASSPORTNO { get; set; }
        public string STATUS { get; set; }
        public string ACCOUNTSTATUS { get; set; }
        public string EXCEPTION { get; set; }
        public string PASSPORTISSUEPLACE { get; set; }
        public string NATIONALITY { get; set; }
        public string OCCUPATION { get; set; }
        public string BONUMBER { get; set; }
        public string NAME { get; set; }
        public string TAXID { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> PASSPORTISSUEDATE { get; set; }
        public string SHORTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string INTRODUCERACREF { get; set; }
        public string POWEROFATTORN { get; set; }
        public string ACCOUNTCATEGORY { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string SECONDHOLDER { get; set; }
        public Nullable<System.DateTime> PASSPORTEXPIREDATE { get; set; }
        public string EMAIL { get; set; }
        public string FATHERNAME { get; set; }
        public byte[] SIGNATURE { get; set; }
        public string GENDER { get; set; }
        public string MOTHERNAME { get; set; }
        public string ORGANIZATIONACCOUNT { get; set; }
        public string NATIONALID { get; set; }
    }
}
