//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPO
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string EXCEPTIONDETAILS { get; set; }
        public string INVESTORNAME { get; set; }
        public string SEQUENCENO { get; set; }
        public string ISIN { get; set; }
        public string STATUS { get; set; }
        public string BOACCOUNTSTATUS { get; set; }
        public string INVESTORACREF { get; set; }
        public string BOCATEGORY { get; set; }
        public Nullable<decimal> LOCKINQTY { get; set; }
        public Nullable<decimal> CURRENTQTY { get; set; }
        public string PROCESSFLAG { get; set; }
        public Nullable<System.DateTime> EFFECTIVEDATE { get; set; }
        public string BOID { get; set; }
        public string INSTRUMENTNAME { get; set; }
        public Nullable<System.DateTime> BUSINESSDATE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> FACEVALUE { get; set; }
        public Nullable<decimal> PREMIUM { get; set; }
        public Nullable<System.DateTime> LOCKINEXPIRY { get; set; }
    }
}
