//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_GROUP_MEMBERS
    {
        public decimal ID { get; set; }
        public decimal GROUP_ID_FK { get; set; }
        public Nullable<decimal> USER_ID_FK { get; set; }
        public Nullable<decimal> GROUP_MEMBER_ID_FK { get; set; }
        public decimal SECURITY_GROUP_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_ON { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    
        public virtual MD_GROUPS MD_GROUPS { get; set; }
        public virtual MD_GROUPS MD_GROUPS1 { get; set; }
        public virtual MD_USERS MD_USERS { get; set; }
    }
}
