//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_PROJECTS
    {
        public MD_PROJECTS()
        {
            this.MD_APPLICATIONS = new HashSet<MD_APPLICATIONS>();
            this.MD_CONNECTIONS = new HashSet<MD_CONNECTIONS>();
            this.MIGR_DATATYPE_TRANSFORM_MAP = new HashSet<MIGR_DATATYPE_TRANSFORM_MAP>();
        }
    
        public decimal ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string COMMENTS { get; set; }
        public decimal SECURITY_GROUP_ID { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_ON { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    
        public virtual ICollection<MD_APPLICATIONS> MD_APPLICATIONS { get; set; }
        public virtual ICollection<MD_CONNECTIONS> MD_CONNECTIONS { get; set; }
        public virtual ICollection<MIGR_DATATYPE_TRANSFORM_MAP> MIGR_DATATYPE_TRANSFORM_MAP { get; set; }
    }
}
