//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public string REFERENCE { get; set; }
        public string NAME { get; set; }
        public string CAPTION { get; set; }
        public string MENUTYPE { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public string PARAMETER { get; set; }
        public string PARENTNAMEID { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<decimal> ORDERINDEX { get; set; }
        public string SETTINGSGROUP { get; set; }
        public string ICON { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
