//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICULARS_VIEW
    {
        public string CODE { get; set; }
        public string PARTICULARSNAME { get; set; }
        public string GROUPNAME { get; set; }
        public string SUBGROUPNAME { get; set; }
        public Nullable<System.DateTime> TRANSACTIONDATE { get; set; }
        public Nullable<decimal> PRINCIPALAMOUNT { get; set; }
        public decimal LIMITMINIMUM { get; set; }
        public string REMARKS { get; set; }
    }
}
