//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIOD
    {
        public PERIOD()
        {
            this.JOURNALHEADs = new HashSet<JOURNALHEAD>();
        }
    
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string FINANCIALYEAR_REFERENCE { get; set; }
        public Nullable<decimal> PERIODINDEX { get; set; }
        public Nullable<System.DateTime> DATEFROM { get; set; }
        public Nullable<System.DateTime> DATETO { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
    
        public virtual FINANCIALYEAR FINANCIALYEAR { get; set; }
        public virtual ICollection<JOURNALHEAD> JOURNALHEADs { get; set; }
    }
}
