//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLEDGE
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string PLEDGEEBOID { get; set; }
        public Nullable<System.DateTime> SETUPDATE { get; set; }
        public Nullable<decimal> PLEDGEQTY { get; set; }
        public string ISINSHORTNAME { get; set; }
        public string TRANSACTIONTYPE { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public Nullable<decimal> BALANCEPLEDGEQTY { get; set; }
        public Nullable<decimal> PLEDGEVALUE { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> BALANCEPLEDGEVALUE { get; set; }
        public string ISIN { get; set; }
        public string PLEDGORBOSHORTNAME { get; set; }
        public string SEQNO { get; set; }
        public string PLEDGORBOID { get; set; }
        public string PLEDGEEBOSHORTNAME { get; set; }
        public Nullable<System.DateTime> BUSINESSDATE { get; set; }
        public string PLEDGESTATUS { get; set; }
        public Nullable<decimal> UNPLEDGEQTY { get; set; }
        public string INVESTORACREF { get; set; }
    }
}
