//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTFOLIOINSTRUMENT
    {
        public string INSTRUMENT { get; set; }
        public Nullable<decimal> NETBALANCE { get; set; }
        public Nullable<decimal> MATUREDBALANCE { get; set; }
        public Nullable<decimal> AVERAGECOST { get; set; }
        public Nullable<decimal> TOTALCOST { get; set; }
        public Nullable<decimal> MARKETRATE { get; set; }
        public Nullable<decimal> MARKETVALUE { get; set; }
        public Nullable<decimal> UNREALIZEDGAIN { get; set; }
        public Nullable<decimal> REALIZEDGAIN { get; set; }
        public Nullable<decimal> PERATIO { get; set; }
        public Nullable<decimal> PERCENTAGEGAIN { get; set; }
    }
}
