//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICEINDEX
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public Nullable<System.DateTime> TRADINGDATE { get; set; }
        public Nullable<decimal> NOOFTRADES { get; set; }
        public string INSTRUMENTREF { get; set; }
        public Nullable<decimal> HIGHESTPRICE { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<System.DateTime> IMPORTDATE { get; set; }
        public Nullable<decimal> LOWESTPRICE { get; set; }
        public string MARKET { get; set; }
        public Nullable<decimal> VARIATION { get; set; }
        public Nullable<decimal> CLOSINGPRICE { get; set; }
        public Nullable<decimal> OPENINGPRICE { get; set; }
        public string ISIN { get; set; }
        public string STATUS { get; set; }
    }
}
