//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRIPTTRANSFER
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string INSTRUMENTACREF { get; set; }
        public string TRANSACTIONTYPE { get; set; }
        public string CERTIFICATENO { get; set; }
        public Nullable<decimal> SHAREQTY { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> HOWLANUMBER { get; set; }
        public Nullable<System.DateTime> ENTRYDATE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string LOWERLIMIT { get; set; }
        public string UPPERLIMIT { get; set; }
        public string MAXIMUMQTY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string STATUS { get; set; }
        public string ISFORGOTTRADEORDER { get; set; }
    
        public virtual INSTRUMENT INSTRUMENT { get; set; }
    }
}
