//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTLEMENT
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string DOCUMENTNO { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string TRANSACTIONTYPE { get; set; }
        public string COUNTERBOID { get; set; }
        public string EXCEPTION { get; set; }
        public Nullable<System.DateTime> TRANDATE { get; set; }
        public string CDBLREFERENCE { get; set; }
        public string BOID { get; set; }
        public string STATUS { get; set; }
        public string INVESTORREF { get; set; }
        public string ISIN { get; set; }
        public string INSTRUMENTREF { get; set; }
        public Nullable<decimal> CHARGE { get; set; }
        public string CERTIFICATENO { get; set; }
    }
}
