//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNATORY
    {
        public SIGNATORY()
        {
            this.SIGNATORYDETAILS = new HashSet<SIGNATORYDETAIL>();
        }
    
        public string Reference { get; set; }
        public string Code { get; set; }
        public string ReportName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string TITLE { get; set; }
    
        public virtual ICollection<SIGNATORYDETAIL> SIGNATORYDETAILS { get; set; }
    }
}
