//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentManagement.InvestmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADE
    {
        public string REFERENCE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public Nullable<decimal> NETAMOUNT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string INSTRUMENTCATEGORY { get; set; }
        public Nullable<decimal> REALIZEDGAIN { get; set; }
        public string BROKERREF { get; set; }
        public string BRANCHREF { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> SHAREQUANTITY { get; set; }
        public Nullable<System.DateTime> TRANSACTIONTIME { get; set; }
        public string MODIFICATIONLOGS { get; set; }
        public Nullable<decimal> TOTALCHARGE { get; set; }
        public string MARKET { get; set; }
        public Nullable<System.DateTime> TRANSACTIONDATE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string ISEXCEPTION { get; set; }
        public Nullable<decimal> COMMISSION { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public string FILENAME { get; set; }
        public Nullable<decimal> INVESTORPAYABLE { get; set; }
        public Nullable<decimal> LAGA { get; set; }
        public string TRANSACTIONTYPE { get; set; }
        public string MEMO { get; set; }
        public string EXCEPTIONDETAILS { get; set; }
        public Nullable<decimal> BROKERPAYABLE { get; set; }
        public string TRADER { get; set; }
        public string INSTRUMENT_REFERENCE { get; set; }
        public string BROKER_REFERENCE { get; set; }
        public string ORDERNO { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public string EXCEPTIONCODE { get; set; }
        public string CONTRACTNO { get; set; }
        public Nullable<decimal> HOWLA { get; set; }
        public string INVESTORACREF { get; set; }
        public Nullable<decimal> BORN { get; set; }
        public string FILETYPE { get; set; }
        public string HOWLATYPE { get; set; }
        public string FOREIGNFLAG { get; set; }
        public string COMPSPOTID { get; set; }
        public Nullable<System.DateTime> MATUREDDATE { get; set; }
        public string ISDEALER { get; set; }
        public string AGENCY { get; set; }
        public Nullable<decimal> AGENCYCOMMISION { get; set; }
        public string STOCKEXCHANGE { get; set; }
    
        public virtual BROKER BROKER { get; set; }
        public virtual INSTRUMENT INSTRUMENT { get; set; }
    }
}
